spring:
  application.name: restaurant-management-system
  datasource:
    url: "jdbc:postgresql://localhost:5432/"
    username: "postgres"
    password: "coditas@"
    jpa:
      properties.hibernate.default_schema: "dev"
      hibernate.ddl_auto: update

server:
  servlet:
    context-path: "/api"

Jwt:
  SECRET: "Coditas@12093!18203@91823#09128$30298%30123^76543&12145*12245"
  EXPIRATION: 8640000